In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"iphone_sales.csv")
df

,OrderID,Model,Color,StorageGB,Price,Quantity,SaleDate,City
0,1,iPhone 15,Black,128,79900,1,2026-01-05,Pune
1,2,iPhone 15 Pro,Blue,256,134900,1,2026-01-06,Mumbai
2,3,iPhone 14,White,128,69900,2,2026-01-07,Pune
3,4,iPhone 15 Pro Max,Natural,512,159900,1,2026-01-08,Delhi
4,5,iPhone SE,Red,64,49900,3,2026-01-09,Nashik
5,6,iPhone 15,Pink,128,79900,2,2026-01-10,Mumbai
6,7,iPhone 14,Blue,256,79900,1,2026-01-11,Pune
7,8,iPhone 15 Pro,Black,512,149900,1,2026-01-12,Bangalore
8,9,iPhone 13,Green,128,59900,2,2026-01-13,Delhi
9,10,iPhone 15 Pro Max,Blue,256,144900,1,2026-01-14,Mumbai

In [11]:
df['Price']=pd.to_numeric(df['Price'])
df['Quantity']=pd.to_numeric(df['Quantity'])
df

,OrderID,Model,Color,StorageGB,Price,Quantity,SaleDate,City
0,1,iPhone 15,Black,128,79900,1,2026-01-05,Pune
1,2,iPhone 15 Pro,Blue,256,134900,1,2026-01-06,Mumbai
2,3,iPhone 14,White,128,69900,2,2026-01-07,Pune
3,4,iPhone 15 Pro Max,Natural,512,159900,1,2026-01-08,Delhi
4,5,iPhone SE,Red,64,49900,3,2026-01-09,Nashik
5,6,iPhone 15,Pink,128,79900,2,2026-01-10,Mumbai
6,7,iPhone 14,Blue,256,79900,1,2026-01-11,Pune
7,8,iPhone 15 Pro,Black,512,149900,1,2026-01-12,Bangalore
8,9,iPhone 13,Green,128,59900,2,2026-01-13,Delhi
9,10,iPhone 15 Pro Max,Blue,256,144900,1,2026-01-14,Mumbai

In [17]:
df['TotalAmount']=df['Price']*df['Quantity']
df['TotalAmount']

0     79900
1    134900
2    139800
3    159900
4    149700
5    159800
6     79900
7    149900
8    119800
9    144900
Name: TotalAmount, dtype: int64

In [22]:
df

,OrderID,Model,Color,StorageGB,Price,Quantity,SaleDate,City,TotalAmount
0,1,iPhone 15,Black,128,79900,1,2026-01-05,Pune,79900
1,2,iPhone 15 Pro,Blue,256,134900,1,2026-01-06,Mumbai,134900
2,3,iPhone 14,White,128,69900,2,2026-01-07,Pune,139800
3,4,iPhone 15 Pro Max,Natural,512,159900,1,2026-01-08,Delhi,159900
4,5,iPhone SE,Red,64,49900,3,2026-01-09,Nashik,149700
5,6,iPhone 15,Pink,128,79900,2,2026-01-10,Mumbai,159800
6,7,iPhone 14,Blue,256,79900,1,2026-01-11,Pune,79900
7,8,iPhone 15 Pro,Black,512,149900,1,2026-01-12,Bangalore,149900
8,9,iPhone 13,Green,128,59900,2,2026-01-13,Delhi,119800
9,10,iPhone 15 Pro Max,Blue,256,144900,1,2026-01-14,Mumbai,144900

In [21]:

total_revenue=df['TotalAmount'].sum()
print(f"Total iphone Revenue: R{total_revenue}")

Total iphone Revenue: R1318500

In [25]:
model_sales=df.groupby('Model')['Quantity'].sum().sort_values(ascending=False)
print("Best Selling iphone Models:")
model_sales

Best Selling iphone Models:

Model
iPhone 14            3
iPhone 15            3
iPhone SE            3
iPhone 13            2
iPhone 15 Pro        2
iPhone 15 Pro Max    2
Name: Quantity, dtype: int64

In [27]:
City_revenue=df.groupby('City')['TotalAmount'].sum().sort_values(ascending=False)
print("city-wise Revenue")
City_revenue

city-wise Revenue

City
Mumbai       439600
Pune         299600
Delhi        279700
Bangalore    149900
Nashik       149700
Name: TotalAmount, dtype: int64

In [28]:
premium_phones=df[df['Price']>100000]
print("premium phones > 1 Lakh:")
premium_phones[['Model','Price','City']]

premium phones > 1 Lakh:

               Model   Price       City
1      iPhone 15 Pro  134900     Mumbai
3  iPhone 15 Pro Max  159900      Delhi
7      iPhone 15 Pro  149900  Bangalore
9  iPhone 15 Pro Max  144900     Mumbai

In [31]:
df.to_csv('iphone_sales_report.csv',index=False)
print("PROJECT COMPLETE! 'iphone_sales_report.csv'")

PROJECT COMPLETE! 'iphone_sales_report.csv'

In [32]:
saved_df=pd.read_csv("iphone_sales_report.csv")
saved_df

,OrderID,Model,Color,StorageGB,Price,Quantity,SaleDate,City,TotalAmount
0,1,iPhone 15,Black,128,79900,1,2026-01-05,Pune,79900
1,2,iPhone 15 Pro,Blue,256,134900,1,2026-01-06,Mumbai,134900
2,3,iPhone 14,White,128,69900,2,2026-01-07,Pune,139800
3,4,iPhone 15 Pro Max,Natural,512,159900,1,2026-01-08,Delhi,159900
4,5,iPhone SE,Red,64,49900,3,2026-01-09,Nashik,149700
5,6,iPhone 15,Pink,128,79900,2,2026-01-10,Mumbai,159800
6,7,iPhone 14,Blue,256,79900,1,2026-01-11,Pune,79900
7,8,iPhone 15 Pro,Black,512,149900,1,2026-01-12,Bangalore,149900
8,9,iPhone 13,Green,128,59900,2,2026-01-13,Delhi,119800
9,10,iPhone 15 Pro Max,Blue,256,144900,1,2026-01-14,Mumbai,144900

In [34]:
import os
print(os.getcwd())

C:\Users\HP